version: '2'
services:
  
  mongo:
    image: mongo:7.0.0
    volumes:
      - data_db:/data/db

  backup:
    # build: .
    image: mongo-backup:1.0.0
    volumes:
      - ./backup:/backup
    depends_on:
      - mongo
    environment:
      MONGO_HOST: 'mongo'
      MONGO_PORT: 27017
      CRON_TIME: '* * * * *'
      INIT_BACKUP: 1

volumes:
  data_db:
    driver: local
